### ISSUE TITLE
Server Error on courselet Concept Tab

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#104]
The following URL generates an 500 Server error:
https://www.courselets.org/ct/teach/courses/5/units/29/concepts/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480184121)

**Comment by cjlee112** [comment]
@maxsocl Only Raccoongang has access to server logs, so please investigate and fix this, it is a blocker for work we need to get done in the course now.

**Comment by VladimirFilonov** [comment]
Problem with logs access, and with exception monitoring could be solved by adding some external logging system, like https://getsentry.com

Senty is available in two ways - SaaS solution or open-source (https://github.com/getsentry/sentry) for self-hosting

**Comment by maxsocl** [comment]
@cjlee112 Problem in `<td><a href="{{ actionTarget |get_object_url:concept }}">` line of concepts.html
Eventually Exception occurs in `Concept.get_url` method:

    return '%s%s/%d/%s' % (basePath, head, objID, tail)
    Exception Type:	TypeError
    Exception Value:%d format: a number is required, not NoneType

This happens due to empty QuierySet `UnitLesson.objects.filter(lesson__concept=self)`:

    for ul in UnitLesson.objects.filter(lesson__concept=self):
        if objID is None or ul.unit_id == unit_id: # in this unit!
            objID = ul.pk

So `objID` is remains `None`.
So there is no UnitLesson where `lesson.concept` is pointed to `self`.

**Comment by maxsocl** [comment]
@cjlee112 Problem in `<td><a href="{{ actionTarget |get_object_url:concept }}">` line of concepts.html
Eventually Exception occurs in `Concept.get_url` method:

    return '%s%s/%d/%s' % (basePath, head, objID, tail)
    Exception Type:	TypeError
    Exception Value:%d format: a number is required, not NoneType

This happens due to empty QuierySet `UnitLesson.objects.filter(lesson__concept=self)`:

    for ul in UnitLesson.objects.filter(lesson__concept=self):
        if objID is None or ul.unit_id == unit_id: # in this unit!
            objID = ul.pk

So `objID` is remains `None`.
So there is no UnitLesson where `lesson.concept` is pointed to `self`.
