### ISSUE TITLE
Short-term LTI credentials for instructors?

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#131]
When working with an instructor at an institution that doesn't already have our LTI credentials in their campus eLearning system, in some cases we might need to give LTI credentials directly to the instructor (e.g. if the campus sysadmin isn't willing to add our credentials right away).  This raises security issues.  One way to mitigate those issues would be to keep two separate sets of LTI credentials, one permanent (for adding to campus eLearning platforms), and one that would expire (and be replaced by a new credential) at the end of every semester.  We would give the latter, short-term credential to instructors who need them for their class that semester.  If the short-term credential gets compromised (e.g. stolen and abused), we could immediately replace that credential without having any impact on the permanent credential used on campus eLearning systems.  

The logic here is that it's a very bad idea to give out the permanent credential to anyone but sysadmins, because if it gets compromised and has to be replaced, that would lock out every LTI student and instructor worldwide!

So the first question is: could our system be modified to support more than one set of LTI credentials?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367484208552)

**Comment by maxsocl** [comment]
@cjlee112 
Sure we can do it.
Now there is basic (system wide) LTI configuration w/o ability to customize secret/keys. But we can develop strategy to create short-term LTI settings.
We can create keys/secret pairs for particular university.
I am going to investigate possible ways to do so and will give a proposal for this feature soon.

**Comment by maxsocl** [comment]
So we are going to modify our LTI provider configuration flow.
I like an idea to move from wide-system LTI settings completely.
We would modify system to work with manually created settings for each LTI consumer.
This settings will be available via Django admin interface.

One question to clarify the new flow: do we want to give a separate LTI credentials to each instructor (even within one e-learning system)?

**Comment by maxsocl** [comment]
Theory
---------

The TC can make choices as to how it manages credentials (keys and secrets) within its system. LTI has three patterns for the credentials: (1) the TC-wide credential for a particular TP domain which is set by the TC administrator and used for all launches to a particular TP domain, or (2) the TC-wide credential for a particular TP URL which is set by the TC administrator and used for all launches to a particular TP URL, or (3) each LTI link is protected by its own credential.  The first and second patterns allow for a more seamless integration between a TC-instance and TP-instance from an instructor’s perspective. The third pattern allows instructors to "mashup" LTI links.

There are two possible credentials associated with a particular basic launch.

1. TC-wide instance guid and secret associated with a particular TP.  The TC-wide instance guid establishes the identity of the TC for launches to a particular TP.  Once the TC-wide secret is established for a TP, all basic launches to the TP’s domain will use this same secret.  Using a TC-wide secret gives TPs the option of trusting user information and context information across multiple contexts within a particular TC instance as being maintained properly by the TC.
In order to select the TC-wide password to be used for a particular basic launch link, the TC examines the domain name in the launch URL for the basic launch link. The TC-wide password is looked up in the list of TC-wide passwords scanning the domain name of the launch URL from right to left.  So for example, if the launch URL was:
http://launch.math.vendor.com/launch.php
The TC would look up the following TC-wide secret keys in order from specific to general: launch.math.vendor.com, math.vendor.com, and then vendor.com.  So when TPs are generating link URLs and giving them to an instructor or embedding those links in a cartridge, it is important to use consistent domain names in those launch URLs so as to be able to match a TC-wide secret for a particular TP with the appropriate launches.
2.       Link-level key and secret associated with a particular link.  This will occur when the basic launch link is directly authored by the instructor within the TC.  This secret will often be produced when the Instructor creates or gains access to a TP content/tool and the TP content/tool provides the instructor with a key and secret associated with the TP link.
Basic launches can happen from the TC with any combination of TC-wide and link-level credentials including one or the other, both, or neither being present. When both are present the launch uses the TC-wide secret to sign the request.
If there is no key/secret combination available for this launch and the TC wants to perform the launch, the TC should not sign the launch data using OAuth. The TC can decide if it wants to send unsigned requests and the TP can decide if it wants to accept unsigned requests. A TC may also choose to treat the lack of key/secret values as an error and refuse to perform the launch.


**LTI credentials management flow should handle two cases:**

1. TC wide LTI configuration - based on instance_guid (for security reason LTI configuration should be linked to tool_consumer_instance_guid if presented)
2. TC per-link Instructor LTI configuration - based on LTI link resouce_id (linked to particular resource_link_id)

But for per-Instructor case per-link configuration is not very useful because Instructor should have a different LTI configuration for each link in Course. Much more better is to use per-instructor LTI credentials.

To achieve this we should properly distinguish LTI requests because each request will have the same set of parameters.
So to implement such behaviour we have to add some **custom value** (parameter) in TC side (Instructor should add custom_value in LTI link settings).


**So proposed implementation is next.**

Instructor have to add some custom param to make it possible to distinguish such request.

So we can handle all request w/o specific custom param as a general request and start to look for LtiConsumer by tool_consumer_instance_guid (first time instance_guid will be added to LtiConsumer founded by consumer_key). Also such LtiConsumer should not have any expiration date.
For request w/ custom param we can look up for **LtiConsumer** by consumer_key. For such **LtiConsumers** we can set expiration date.

Second and more clear way to implement this is to use different models for **LtiConsumers** (we can use **TmpLtiConsumer** name for per-instructor configuration).

General **LtiConsumer** should have **name**, **key**, **secret**, **active** flag, **instance_guid** fields while per-link (per-instructor) **LtiConsumer** should have **name**, **key**, **secret**, **active** flag and **expiration date** fields.


BTW also we need to implement data migration to create first general **LtiConsumer** item based on current django settings (**consumer_key** and **lti_secret**) to migrate currently existent **LtiUsers** to use new **LtiConsumer** model instead of Django settings.

P.S. there is an issue - non standard LTI implementation in **Moodle** (we remember this while implementing such LTI management flow):

- There is an IMS recommendation how to use per-link LTI configuration -  Basic launches can happen from the TC with any combination of TC-wide and link-level credentials including one or the other, both, or neither being present. When both are present the launch uses the TC-wide secret to sign the request.
- But Moodle instance (test.ccle.ucla.edu) has an opposed strategy - if there is per-link credentials and TC wide credentials then per-link credentials will be used.

So on Moodle's systems per-instructor configuration will be used even after adding TC wide LTI settings for our domain.

**Comment by maxsocl** [comment]
@cjlee112

**Comment by cmltaWt0** [comment]
Done
