### ISSUE TITLE
Standard logins Phase 1 specification

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#25]
This issue will consolidate discussion about setting a clear specification for our first project to establish some standard login mechanisms, namely LTI, social-auth, and email-address.  Please use this comment thread to comment on the initial proposal, which I'm going to add as the first comment below.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480187653)

**Comment by cjlee112** [comment]
Rationale
=========

Standard user login mechanisms are a vital step for opening up
courselets.org to instructors and students. In particular, since our
site focuses on active learning exercises (where the student needs to
answer questions and work through follow-up exercises based on their
answers), a user's history of past exercises is crucial to what they're
going to do next. We need them logged in, to keep that history in a
coherent form, but we want to minimize the "barrier to entry" that login
requirements often represent for first-time users.

Goals and Questions
===================

-   to provide a fast path (ideally single-click) for an instructor on
    an LTI consumer site (e.g. UCLA's Moodle) to be added as a
    courselets user, automatically creating:

    -   a courselets User (login) associated with this LTI user ID
    -   a courselets Course associated with this LTI course ID
    -   a courselets Role giving the User instructor role on this
        course.

    Is there a way we can provide a courselets URL once to the LTI
    consumer site, that will enable all instructors on that site to
    click a link provided by that site that will register them on
    courselets as outlined above?

    Need to specify what LTI consumer platforms we're going to test
    against. Do we expect our LTI solution to easily work generically
    with all LTI consumers? What do we think is the "sweet spot" for
    being able to cover the most valuable LTI consumer platforms with
    the least work?

-   to provide a fast path for such an instructor to add on their LTI
    consumer site (e.g. UCLA's Moodle) an LTI link for their students to
    access a specified courselet within their course on courselets.org.
    (I think you've already done this)
-   to provide a single-click path for a student in a course on an LTI
    consumer site to be directed to that courselet, automatically adding
    them as a courselets user if need be (I think you've already done
    this)
    -   a courselets User (login) associated with this LTI user ID
    -   a courselets Role giving the user "enrolled student" role in the
        course.
-   (optional, lower priority) Eventually, we'd like a fast path for an
    instructor to export exercise completion numbers (i.e. count of how
    many exercises each student has completed, out of the total
    assigned) as "grades" back to the LTI consumer site. Courselets is
    not intended to be a grading platform (in the sense of "you got 80%
    of the questions right") but instructors may want to assign points
    simply for performing the exercises (otherwise busy students may not
    bother doing them).
-   social-auth: user can login to courselets.org by clicking "sign in
    with Google" / fb / twitter / LinkedIn, creating a

    -   a courselets User (login) associated with this social-auth

    The user will have access to public (unrestricted) courses on
    courselets.org

-   "session login" via email address: fast path for user to login by
    simply giving an email address.
    -   creates a courselets User (login) with this email address.
        Auto-generate username from the email address?
    -   the user's session is activated (logged in) immediately, and the
        user retains access until the browser session expires.
    -   The user will have access to public (unrestricted) courses on
        courselets.org
    -   email-validation is only required for *later* recovering access
        to an expired session. In this case an email with temporary
        password and "click to validate" URL is sent to the email
        address.
    -   it appears that python-social-auth provides its own backend for
        email validation. Perhaps we should consider using it? Or is
        there a better library specifically for this?
-   login merge mechanisms
    -   "+1 merge": if a user is logged in via one method, they can
        employ a second method (e.g. social-auth), proving that they
        also own the second login, so the second login is merged with
        the first.
        -   obvious: social-auth as second login
        -   also: email-validation as second login
    -   UI can automatically suggest merging if two logins share same
        email. However actual merging should be done via "+1 merge"
        mechanism above, i.e. the *currently logged in user* must prove
        auth to second login, to merge it.

**Comment by auraz** [comment]
Summary of design:

1. System will allow anonymous access. This access will be implemented by creating Django User Id field in table. And that user_id will be random id, hashed by some value, probably course_id, to which anonymous access is granted.
1. As long as anonymous user does some learning, user may want to store its progress. This will be done by providing to user possibility to enter email address. And next time, user will open Courselets site, there will be possibility for user to enter email address and get password by email. With that password user can login, and system will look to the database, and if that email will be found there, session and user history will be restored.
3.System will allow following type of logins:
  * social auth via: twitter, linkedin, Facebook, google and Khan academy (if it is possible)
  * LTI login from the Tool Customer page
  * email/password access
4. System will provide merging mechanism between all those accounts
5. System should work with post LTI customers, which provide right way of LTI implementations
6. LTI launch url will be exact url to corselet and course_id and unit_id will be obtained from the url
7. Implement grading functionality: be able to post back grades to Tool Customers
  * Research to to set up grades values for Courselets problems
  * Grade will be passed for course as a whole
8. Course will be public / not public (implemented in courselets, test this functionality)
9. Email validation will be done by usual django services
10. On user profile page will be possibility to link social and email accounts 
11. UI can automatically suggest merging if two logins share same email, if user is logged via one of that emails
12. When user logs in via different accounts, same user will have different email and credentials. We will store all possible user emails. And we will ask user to choose which credentials to use and which email to use as primary
13. Will will setup login/logoff functionality on following system pages: login, logout, profile pages. Implement those pages.
14. Research on using decorator login_required for accessing courses
15. Social provider metadata will be stored in social auth table, moodle provider metadata will be stored in django-lti table. 
16. Django-lti will store most moodle information in json, but some of moodle data will be stored in special columns for easy indexing and searching: moodle_id and course_id and may be others
17. Same user can come from different moodle accounts. He can't link this accounts straightforward, but he can link them via his facebook account. In this case we will not merge data in moodle table, because rows will have different moodle_id and course_id, we will change only user_id to link to same user. Same is when user come from same moodle provider but using different courses
18. if we didn't get the user's email address from the auth-provider (e.g. LTI consumer) ask the new user to enter their email *optionally*, as an aid to future auto-merge of multiple logins. Keep it optional so that we don't lose new users due to impatience / unwillingness to provide their email address.
19. Expired sessions with no associated email address (or any other auth info) are "orphaned", in the sense that there is no way for the user to authenticate their ownership of that expired session. (i.e. unless we have a permanent identity cookie on their browser, that doesn't expire). Presumably we would eventually delete User records associated with such orphaned sessions (or at least move them "offline" for data mining purposes only). 
20. There is no way to use LTI authentication to merge an LTI-based login into a session where the user has already logged in via social-auth


**Todo list for next two weeks**

1. Implement anonymous access functionality
2. Implement all types of logins
3. Implement right fields in databases
3. Implement merg functionality
4. Fix of lti-specific issues: X_FRAME_OPTIONS, code cleanup
5. Implement grading 
7. Tests.

**Comment by maxsocl** [comment]
Considerations about social auth login in iFrame.
-----------------------------------------------------------------
Should we prevent oauth/oauth2 login in iFrame when user in Moodle external tool can go to profile page and click to social-auth login?

http://tools.ietf.org/html/draft-ietf-oauth-v2-23#section-10.13

    native applications SHOULD use
    external browsers instead of embedding browsers within the
    application when requesting end-user authorization

**Comment by auraz** [comment]
This means we will open new browser tab when user clicks on profile, and from that tab user will be able to login to social accounts. Also we will disallow social logins from iframe.

**Comment by cjlee112** [comment]
This all sounds good.  One additional idea: if we have a login with an associated email address, we should validate that this login (specifically, a session with this login) has access to that email, i.e. we send them email with a random validation code "link to click" and then see that this code link gets loaded by this session.  Then, whenever you have two logins both with the same validated email, you can merge them.  Presumably that would work even if the logins were LTI logins, right?

**Comment by cjlee112** [comment]
Improved definitions:

* **Stranger**: no django user ID
* **Temporary session user**: django user ID and email address, but not yet validated.  Encourage them to click email validation link and / or add social-auth.
* **Validated session user**: django user ID and validated email address.  Encourage them to add social-auth.
* **LTI user**
* **Social-auth user**

**Comment by cjlee112** [comment]
Conclusions from our discussion today, and above definitions:

* when starting Temporary session user, immediately get email address, send validation email, and tell them to click validation link next time they look at their email.

* login / registration function will be combined on one page

* login/registration page will show different text for each of the above categories.

**Comment by cjlee112** [comment]
Suggestion about displayed name for session users:

* Temporary session user: set their name as "Temporary User", to emphasize that their account is strictly temporary (will be unrecoverable once it expires).

* Validated session user: set their name based on their email address.
