### ISSUE TITLE
[Gaston] Instructors feel that the wording of "error" in "error model" sounds negative and suggest using "misunderstanding" or "misconception" instead.

### ISSUE THREAD

**Issue by cmltaWt0** [cjlee112/socraticqs2#349]

**Comment by maxsocl** [comment]
@cjlee112 We need to discuss this issue

**Comment by redilonka** [comment]
Decided to postpone until Instructor MVP release.

**Comment by cjlee112** [comment]
For a generic, top-level term, I've been switching to "blindspot" instead of "misconception".  It is value-neutral, and better captures the key idea of "the unknown unknowns".  This also raises the question of whether this term could be extended to give an improved term for "error model", e.g. a "diagnosed blindspot".  We can discuss this.

**Comment by cjlee112** [comment]
Or maybe "known blindspot", which maps directly to what people call "the known unknowns"

**Comment by cmltaWt0** [comment]
Can we close this?
