### ISSUE TITLE
[Sharing]Student can get access to a course by opening /ctms page

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#426]
STR: 
Open the /ctms page through student with whom ypu shared a course

ER: Student sees course only in "shared" page and dont have access to it

AR: Student sees course on the /ctms page and have access to it

**Comment by alexbojko** [comment]
I designed a little bit another flow for invites:
 * Instructor create new invite
 * * System send email to desired user
 * Student/Tester go to /ctms
 *  Open Shared courses and see new one shared course
 * User click on the link and it will open course (here link is the same as in email, so he will join course properly)
 * From instructor side:
 * * Instructor will see that user has been joined as Student/Tester

I thought that it's not require user to follow link from email, because he will see new shared course and he must be able to join it right now.
