### ISSUE TITLE
Validation account link links to the OLD instructor UI

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#477]
STR:
1. Create a new account and proceed by a link in the confirmation letter

ER: New instructor UI is opened

**Comment by alexbojko** [comment]
@DenisKolesnik if you used /signup/ page to create account - this is default behavior because once we created new user we create Instructor object for this user. 

When user open confirmation link from email system check - if user has instructor - it will show new UI, if no instructor - old UI will be shown.

**Comment by DenisKolesnik** [comment]
@alexbojko So I think we should add redirect to the new Instructor UI, cause even if user is redirected to the old UI (Like it works now). he can just write /ctms in the URL field and proceed to the new UI.
