### ISSUE TITLE
The Internal server error 500 appears when open error models tab of concept

### ISSUE THREAD

**Issue by DenisKolesnik** [cjlee112/socraticqs2#621]
Link: https://www.courselets.org/ct/teach/courses/27/units/151/concepts/6678/errors/
_Looks like when concept doesn't have any error models - the 500 error appears instead of page with empty list_

UPD:
When someone deleted UnitLesson associated with error model from concept, it returns 500 error.

[SOLUTION]

Wrap method Concept.get_url with try\except. In the usual way, it will return path, as desired, in the case of exception (if no UL associated with Concept) it will return '#' to avoid of crashing the whole page.

**Comment by alexbojko** [comment]
There were no UnitLesson associated with needed Concept, that's why we get 500 error.

I fixed it on server, just created UnitLesson for this concept.

As we discussed with @rimikt we have to do some fixes to handle this case:
 * if Concept can not build path properly it will return '#' instead of path
 * if UL  can not build path properly it will return '#' instead of path (not required for now)

**Comment by alexbojko** [comment]
error was 
<img width="1230" alt="screenshot at aug 07 20-22-40" src="https://user-images.githubusercontent.com/370714/29037900-41e2f6ae-7bae-11e7-8a59-0a30c2060790.png">

**Comment by redilonka** [comment]
tested on a stage

**Comment by redilonka** [comment]
tested on a prod 
only for concept
