### ISSUE TITLE
Specify the time zone along with the time stamps in JSON course report

### ISSUE THREAD

**Issue by xqrongm** [cjlee112/socraticqs2#634]
follow-up to #608 
Please specify the time zone along with the time stamps. e.g. 11 am UTC-4:00, 8 am UTC-7:00, etc. - So that each user will know if it's in his/her own time zone by just looking at the time stamp itself, instead of having to verify with their clock. Thanks!

**Comment by rimikt** [comment]
@xqrongm 
This feature won't be fixed due to some internal Django's specifics.
I do not want to complicate code application.
May be we need to discuss different approach to achieve our goal.
Possible solution is to store Student timezone somewhere in profile and render it in reports for an instructor.
