### ISSUE TITLE
Don't default to Answers tab unless there are answers

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#755]
Currently, clicking a thread in the sidebar will display its Answers tab, even if the thread is an Introduction (not even a Question, which raises the issue, why does an Introduction even have an Answers tab in the first place?).  When an instructor is trying to write a courselet this is both annoying (because you want to Edit Thread, but it keeps sending you to Answers), and senseless (because you know that the system knows that there AREN'T any answers yet, which makes our UI seem unpolished and unprofessional).  I think the best fix right now is to default to Answers ONLY if there actually are student answers for that thread (otherwise default to Edit Thread).

**Comment by cmltaWt0** [comment]
@cjlee112 I've reviewed our Confluence documentation for this case and there are not any Acceptance criteria for Sidebar behavior :(
I'm going to change the current behavior to the following:
1. Compose link to an Answer tab in case a Thread is ORCT AND it has at least one Student response
2. Compose link to an Edit tab in case a Thread is NOT ORCT OR it has no any Student responses

@karluxd FYI
We need to add this to Confluence.

@redilonka ^

**Comment by karluxd** [comment]
@cmltaWt0 The doc for the sidebar is available here https://karluxd.atlassian.net/wiki/spaces/COUR/pages/21633899/Navigation+-+Sidebar+Navigation. The links should take you to `8. Unit` which always shows `8.1 Edit` as explained here https://karluxd.atlassian.net/wiki/spaces/COUR/pages/21604124/8.+Unit. I'll add the sidebar as a top-level feature so that it's easier to find this again. We can also update the descriptions here to be more explicit later on. Let me know if you're looking for something else or have any questions 🙂 

As far as I can recall, we haven't talked about sending people to answers from the sidebar. I'd rather keep it consistent and always take them to the same place (edit). We should however lead them towards important content, e.g. new blindspots/answers, by highlighting these links in different places eventually. 

@cjlee112 Do you think it's important to link them to answers from the sidebar when they are available, or can we always send them to edit as we've discussed previously?

**Comment by karluxd** [comment]
I see that there are some references to old things here as well, e.g. Add Units by Chat. It feels like it's time for us to spend more time on keeping all of our documents and test cases up to date now, even if it means that we'll have less time to build and test new things. It will be very easy to lose the new instructors if they are confused or if things are not working as expected. In addition to the onboarding that we're working on, maybe we should review all features and texts in the app again to ensure that things are working properly before these invites are sent @cjlee112?

**Comment by cjlee112** [comment]
@karluxd It's fine with me to follow your principle of consistency, i.e. clicking a thread in the sidebar always sends you to Edit Thread.
