### ISSUE TITLE
can Chat FSM run an ORCT as an error model resolution?

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#781]
in connection with issue #780, here is a simple flow for presenting an ORCT question + answer as a Resolution for an error model:

![resolutionorct](https://user-images.githubusercontent.com/59820/52675905-241c5f00-2edd-11e9-9e69-149eb9fb91ec.png)

**Comment by cjlee112** [comment]
@redilonka Please mark this as Closed if it passed your tests, otherwise report whatever problems you found.

**Comment by redilonka** [comment]
all tests was passed exept this one 
https://github.com/cjlee112/socraticqs2/issues/787

**Comment by cmltaWt0** [comment]
@cjlee112 @redilonka is I mentioned last month this issue #787 required additional effort due to initial wrong architecture so it was no estimated and planned to do this release.
This is known behavior till we take this issue into release.
So I propose to close this task and work only on #787 as we want just to remove one unnecessary message.
